# Generated by Django 6.0.7 on 2026-07-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_alter_customuser_managers_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog_files/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
